### PR TITLE
Added new Socket Client for FDGT

### PR DESCRIPTION
**Pull request by CrypticEnigma00**
Added new Socket Client for FDGT to be able to test the Twitch API's functionality i.e. Raid's, Bit's, Etc

### CODE REVIEW

**Comment by CrypticEngima** [comment]
FDGT is a drop in replacement for the Twich API found  @ [FDGT.dev](FDGT.dev) it is created by TrezzyCodes on twitch

**Comment by trezy** [comment]
@CrypticEngima Can you comment with an example of how this would be used?

Also, I'm not convinced that the `fdgt` client needs to be built into the lib. There's a non-zero chance that I change the name in the near future. There will be plenty of heads up and the URLs would still work, but it'd cause all sorts of confusion for users of any lib that has `fdgt` hardcoded into it. As long the `WebSocketClient.Url` has a setter, this should all be fine.

That said, it may be worth ensuring that the URL can be set for `TcpClient`, too, as `fdgt` supports both protocols and I'd hate to see folx that are using a normal IRC connection be excluded. 😁

**Comment by RamblingGeekUK** [comment]
I tried just adding/changing the setter and it didn't seem to work :-(

**Comment by Dracaratos** [comment]
https://i.imgur.com/8nhaJQX.png I modified this in `TwitchLib.Communication.Enums.ClientType` so it would accept a custom URL, then `TwitchLib.Communication.Client.WebsocketClient` I modified the constructor as follows https://i.imgur.com/fJl5nVW.png

Unsure if it works, but thought I'd post it here just in case as I was trying to refactor some of it for personal use but gonna change direction.

**Comment by CrypticEngima** [comment]
> @CrypticEngima Can you post an example of how this would be used?
> 
> Also, I'm not convinced that the `fdgt` client needs to be built into the lib. There's a non-zero chance that I change the name in the near future. There will be plenty of heads up and the URLs would still work, but it'd cause all sorts of confusion for users of any lib that has `fdgt` hardcoded into it. As long the `WebSocketClient.Url` has a setter, this should all be fine.
> 
> That said, it may be worth ensuring that the URL can be set for `TcpClient`, too, as `fdgt` supports both protocols and I'd hate to see folx that are using a normal IRC connection be excluded. 😁

@trezy 

I spoke with LuckyNoS7evin about the fix to allow fdgt to work with the Library after I implamented the same fix as @Dracaratos. He said that he wanted it done as a seperate client in this library so that is what I have done. I looked through thr current implamentation and there is currently no way to send a URL through the credentials as suggested by the signature on the  ConnectionCredentials class the current implamentation of the WebSocket class is hard coded to only work with Twitch itself. after speaking with LuckNoS7evin he was saying that he is about to embark on writing V4 of the TwitchLib and would include the ability to use fdgt in that. I would like to see this API be able to have a URL override capability implamented as I think it would be the most flexible way to handle drop in replacments for Twitch API. Thanks Trezzy I missed that there was a TCP client reading the docs on fdgt.dev , I can update this PR to allow the TCP connection not just the websocket if it would be usefull. If this is the case I would rename this current fdgt class to FDGTWebSocketClient and have the TCP client as FDGTClient to try and follow current naming standards in the TwitchLib API I only named it FDGTClient as I thought the websocket was the only way to connect to fdgt.

I do take into account here that you may change the name of fdgt but in this current implamentation of TwitchLib that would require a PR to update the URL. 

@RamblingGeekUK the URL's are hardcoded at the WebSocketClient class based on the ClientOptions selected. 

Example usage : 
using the TwitchLib current documentation as a guide (Please replace any occurance of {{value}} with actual values removing the entire placeholder text), I have taken this from my testing app wich was connecting and receiving the raid message from fdgt: 

using System;
using TwitchLib.Client;
using TwitchLib.Client.Enums;
using TwitchLib.Client.Events;
using TwitchLib.Client.Extensions;
using TwitchLib.Client.Models;
using TwitchLib.Communication.Clients;
using TwitchLib.Communication.Models;


namespace Basic_Twitch_Chat
{
	class Program
	{
		static void Main(string[] args)
		{
			Bot bot = new Bot();
			Console.ReadLine();
		}
	}

	class Bot
	{
		TwitchClient client;

		public Bot()
		{
			ConnectionCredentials credentials = new ConnectionCredentials({{TwitchUsername}}, {{OAuthToken}});
			var clientOptions = new ClientOptions
			{
				MessagesAllowedInPeriod = 750,
				ThrottlingPeriod = TimeSpan.FromSeconds(30)
			};

			WebSocketClient customClient = new FDGTClient(clientOptions);
			client = new TwitchClient(customClient);
			client.Initialize(credentials, {{ChannelName}});

			client.OnLog += Client_OnLog;
			client.OnJoinedChannel += Client_OnJoinedChannel;
			client.OnMessageReceived += Client_OnMessageReceived;
			client.OnWhisperReceived += Client_OnWhisperReceived;
			client.OnNewSubscriber += Client_OnNewSubscriber;
			client.OnConnected += Client_OnConnected;
			client.OnRaidNotification += Client_OnRaidNotification;
			client.OnChatCommandReceived += Client_OnCommandReceived;

			client.Connect();
		}

		private void Client_OnCommandReceived(object sender, OnChatCommandReceivedArgs e)
		{
			
		}

		private void Client_OnRaidNotification(object sender, OnRaidNotificationArgs e)
		{
			Console.WriteLine($"Raid Notification Recieved: user:{e.RaidNotification.DisplayName} , Raw Msg: {e.RaidNotification.SystemMsg}");
		}

		private void Client_OnLog(object sender, OnLogArgs e)
		{
			Console.WriteLine($"{e.DateTime}: {e.BotUsername} - {e.Data}");
		}

		private void Client_OnConnected(object sender, OnConnectedArgs e)
		{
			Console.WriteLine($"Connected to {e.AutoJoinChannel}");
			
		}

		private void Client_OnJoinedChannel(object sender, OnJoinedChannelArgs e)
		{
			Console.WriteLine("Hey guys! I am a bot connected via TwitchLib!");
			client.SendMessage(e.Channel, "Hey guys! I am a bot connected via TwitchLib!");
			SendRaid();
		}

		private void Client_OnMessageReceived(object sender, OnMessageReceivedArgs e)
		{
			if (e.ChatMessage.Message.Contains("badword"))
				client.TimeoutUser(e.ChatMessage.Channel, e.ChatMessage.Username, TimeSpan.FromMinutes(30), "Bad word! 30 minute timeout!");
		}

		private void Client_OnWhisperReceived(object sender, OnWhisperReceivedArgs e)
		{
			if (e.WhisperMessage.Username == "my_friend")
				client.SendWhisper(e.WhisperMessage.Username, "Hey! Whispers are so cool!!");
		}

		private void Client_OnNewSubscriber(object sender, OnNewSubscriberArgs e)
		{
			if (e.Subscriber.SubscriptionPlan == SubscriptionPlan.Prime)
				client.SendMessage(e.Channel, $"Welcome {e.Subscriber.DisplayName} to the substers! You just earned 500 points! So kind of you to use your Twitch Prime on this channel!");
			else
				client.SendMessage(e.Channel, $"Welcome {e.Subscriber.DisplayName} to the substers! You just earned 500 points!");
		}

		private void SendRaid()
		{
			Console.WriteLine("Sending Raid Message");
			client.SendMessage({{channel}}, "raid --username drdisrespectlive --viewercount 10000");
		}
	}
}

**Comment by itssimple** [comment]
While we wait for a solution on either how to change the URL or if we should create our own packages for IClients, I can provide an ugly hack to solve this.

I used reflection to grab the IClient (in this case the WebSocketClient), and then from there grabbed the field for the Url, and set the value with reflection as well.

It works if you wanna get going with [fdgt](https://fdgt.dev) right now. :)

https://gist.github.com/itssimple/d5afe8a21ddfe52772e07f8dc0b9d433

**Comment by Syzuna** [comment]
Communications got a rewrite.
In the new version you will be able to overwrite the URL

**Pull request closed without merging**
