### PR TITLE
Async Task Events

### PR DESCRIPTION
**Pull request by GimliCZ**
avoid async void events
Async Task Events are much safer
Reference: https://medium.com/@a.lyskawa/the-hitchhiker-guide-to-asynchronous-events-in-c-e9840109fb53

### CODE REVIEW

**Comment by AoshiW** [comment]
Why is the delegate placed in the class?

**Comment by GimliCZ** [comment]
Yep. That is mistake. For some reason I forgot to get it out. 
I will fix it ASAP

**Comment by GimliCZ** [comment]
> Are there any side effects from this change? 
- Yes. Async task increases slightly overhead. 

> Or any user api facing changes?
- Yes. Some events will have to be changed from void or async void to Task or async Task, if needed

- I did write reason why I dare to make those changes, bellow.

TL;DR: 
Safety improvements and performance improvements are worth of small change in event calling. As result we can make whole TwitchLib better.



- I will do example on twitch client.

HandlePrivMsg(IrcMessage ircMessage) is not light function. It also has multitude of events. Since you are running them asynchronusly and not waiting them, you are "Fire and forgeting" them.

As a result, this can cause uncatchable exceptions

- (Current branch):

 ```
 private async Task HandleIrcMessageAsync(IrcMessage ircMessage)
        {
            if (ircMessage.ToString().StartsWith(":tmi.twitch.tv NOTICE * :Login authentication failed"))
            {
                OnIncorrectLogin?.Invoke(this, new OnIncorrectLoginArgs { Exception = new ErrorLoggingInException(ircMessage.ToString(), TwitchUsername) });
                return;
            }
            
            switch (ircMessage.Command)
            {
                case IrcCommand.PrivMsg:
                    HandlePrivMsg(ircMessage);
                    return;
                case IrcCommand.Notice:
                    await HandleNoticeAsync(ircMessage);
                    break;
                case IrcCommand.Ping:
                    if (!DisableAutoPong)
                        SendRaw("PONG");

```

- (My branch)

```

        private async Task HandleIrcMessageAsync(IrcMessage ircMessage)
        {
            if (ircMessage.ToString().StartsWith(":tmi.twitch.tv NOTICE * :Login authentication failed"))
            {
                if (OnIncorrectLogin != null) await OnIncorrectLogin?.Invoke(this, new OnIncorrectLoginArgs { Exception = new ErrorLoggingInException(ircMessage.ToString(), TwitchUsername) });
                return;
            }

            switch (ircMessage.Command)
            {
                case IrcCommand.PrivMsg:
                    await HandlePrivMsg(ircMessage); //this can be run fully async
                    return;
                case IrcCommand.Notice:
                    await HandleNoticeAsync(ircMessage);
                    break;
                case IrcCommand.Ping:
                    if (!DisableAutoPong)
                        SendRaw("PONG"); //this can be changed to SendRawAsync since its fully async
```

**Review by Syzuna — APPROVED** [review]

**Comment by Syzuna** [comment]
LGTM thx

**Pull request merged**
